experiments:
  grpo-trl:
    entrypoint: |
      uv sync --frozen && uv run python -m src.runners.grpo
    image: 189709136206.dkr.ecr.us-east-1.amazonaws.com/plasmidrl-ray-cpu-uv:latest
    needs_gpu: true
    gpu_family: g6
    num_gpus: 1
    ttl_seconds: 10800
    env:
      WANDB_PROJECT: plasmidrl-trl-grpo
      WANDB_TAGS: '["plasmid","rl","trl","grpo"]'
      WANDB_NOTES: TRL GRPO training on plasmid design

  es:
    entrypoint: |
      uv sync --frozen && uv run python -m src.runners.es
    image: 189709136206.dkr.ecr.us-east-1.amazonaws.com/plasmidrl-ray-cpu-uv:latest
    needs_gpu: false
    num_gpus: 0
    ttl_seconds: 7200
    env:
      WANDB_PROJECT: plasmidrl-trl-es
      WANDB_TAGS: '["plasmid","rl","trl","es"]'
      WANDB_NOTES: TRL Evolution Strategies optimization

  verl-ppo:
    entrypoint: |
      echo 'Starting VERL PPO...' && python3 -m verl.trainer.main_ppo --config-name verl_ppo
    image: verlai/verl:base-verl0.5-cu126-cudnn9.8-torch2.7.1-fa2.7.4
    needs_gpu: true
    gpu_family: g6
    num_gpus: 1
    ttl_seconds: 14400
    env:
      WANDB_PROJECT: plasmidrl-verl-ppo
      WANDB_TAGS: '["plasmid","rl","verl","ppo"]'
      WANDB_NOTES: VERL PPO trainer

  verl-grpo:
    entrypoint: |
      echo 'Starting VERL GRPO...' && python3 -m verl.trainer.main_ppo --config-name verl_grpo
    image: verlai/verl:base-verl0.5-cu126-cudnn9.8-torch2.7.1-fa2.7.4
    needs_gpu: true
    gpu_family: g6
    num_gpus: 1
    ttl_seconds: 14400
    env:
      WANDB_PROJECT: plasmidrl-verl-grpo
      WANDB_TAGS: '["plasmid","rl","verl","grpo"]'
      WANDB_NOTES: VERL GRPO trainer

  infer:
    entrypoint: |
      python -m src.eval.infer
    image: 189709136206.dkr.ecr.us-east-1.amazonaws.com/plasmidrl-ray-cpu-uv:latest
    needs_gpu: true
    gpu_family: g6
    num_gpus: 1
    ttl_seconds: 7200
