name: tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Sync dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest -q

